CanellaPruebaMVC/Models/Automovil.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CanellaPruebaMVC.Models
{
    public class Automovil
    {
        public int Id { get; set; }

        public string Matricula { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public decimal Precio { get; set; }

    }
}

CanellaPruebaMVC/Controllers/AutomovilController.cs
using CanellaPruebaMVC.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CanellaPruebaMVC.Controllers
{
    public class AutomovilController : Controller
    {
        private string UrlApi = "https://localhost:44303/api";
        // GET: Automovil
        public async Task<ActionResult> Index()
        {
            // servicio para obtener la lista de autos
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync($"{UrlApi}/Automovil");
            List<Automovil> response = JsonConvert.DeserializeObject<List<Automovil>>(json);
            return View(response);
        }

        // GET: Automovil/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync($"{UrlApi}/Automovil/{id}");
            Automovil response = JsonConvert.DeserializeObject<Automovil>(json);
            return View(response);
        }

        // GET: Automovil/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Automovil/Create
        [HttpPost]
        public async Task<ActionResult> Create(Automovil Auto)
        {
            try
            {
                // seteo de datos para el post
                var json = JsonConvert.SerializeObject(Auto);
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var httpClient = new HttpClient();
                var response = await httpClient.PostAsync($"{UrlApi}/Automovil", data);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Automovil/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync($"{UrlApi}/Automovil/{id}");
            Automovil response = JsonConvert.DeserializeObject<Automovil>(json);
            return View(response);
        }

        // POST: Automovil/Edit/5
        [HttpPost]
        public  async Task<ActionResult> Edit(int id, Automovil Auto)
        {
            try
            {
                var json = JsonConvert.SerializeObject(Auto);
                var data = new StringContent(json, Encoding.UTF8, "application/json");
                var httpClient = new HttpClient();
                var response = await httpClient.PutAsync($"{UrlApi}/Automovil/{id}", data);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Automovil/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var httpClient = new HttpClient();
            var json = await httpClient.GetStringAsync($"{UrlApi}/Automovil/{id}");
            Automovil response = JsonConvert.DeserializeObject<Automovil>(json);
            return View(response);
        }

        // POST: Automovil/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Automovil collection)
        {
            try
            {
                var httpClient = new HttpClient();
                var json = await httpClient.DeleteAsync($"{UrlApi}/Automovil/{id}");
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CanellaPruebaMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CanellaPruebaMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CanellaPruebaMVC/Views/Automovil/Create.cshtml
@model CanellaPruebaMVC.Models.Automovil

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Automovil</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crear Registro" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CanellaPruebaMVC/Views/Automovil/Delete.cshtml
@model CanellaPruebaMVC.Models.Automovil

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Estás seguro de que quieres eliminar esto?</h3>
<div>
    <h4>Automovil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            @Html.ActionLink("Volver a la lista", "Index")
        </div>
    }
</div>

CanellaPruebaMVC/Views/Automovil/Details.cshtml
@model CanellaPruebaMVC.Models.Automovil

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Automovil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Matricula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Matricula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Regresar a la lista", "Index")
</p>

CanellaPruebaMVC/Views/Automovil/Edit.cshtml
@model CanellaPruebaMVC.Models.Automovil

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Automovil</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Matricula, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Matricula, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Matricula, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Editar Registro" class="btn btn-warning" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CanellaPruebaMVC/Views/Automovil/Index.cshtml
@{
    ViewBag.Title = "Lista de Autos";
}

<h2>Lista de autos</h2>
<br />
<br />
<a href="@Url.Action("Create", "Automovil")" class="btn btn-primary">Crear Registro</a>
<br />
<br />
<table class="table">
    <tr>
        <th>Marca</th>
        <th>Color</th>
        <th>Matricula</th>
        <th>Precio Renta</th>
        <th>Acciones</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>@item.Marca</td>
        <td>@item.Color</td>
        <td>@item.Matricula</td>
        <td>@item.Precio</td>
        <td>
            <!-- Single button -->
            <div class="btn-group">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Acciones <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="@Url.Action("Edit", "Automovil", new { id = @item.Id })">Editar</a></li>
                    <li><a href="@Url.Action("Details", "Automovil", new { id = @item.Id })">Detalle</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="@Url.Action("Delete", "Automovil", new { id = @item.Id })">Eliminar</a></li>
                </ul>
            </div>
        </td>
    </tr>
}

</table>

CanellaPruebaMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CanellaPruebaMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CanellaPruebaMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CanellaPruebaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Automovil", "Index", "Automovil")</li>
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>